sl_light_texture = texture;  // Index de la texture de lumière
sl_light_xscale  = scale;         // Facteurs d'étirement de la lumière
sl_light_yscale  = scale;
sl_light_color   = color;        // Couleur de la lumière
sl_light_shadowsharpness = shadow_sharpness; // Facteur de dureté des ombres
sl_light_shadowlength = shadow_length
sl_light_shadowfactor = shadow_factor
sl_light_ambientpower = ambient_power
sl_light_angle = angle
sl_light_power = power1